services:
  - type: web
    name: ai-content-analyzer-api
    env: node
    buildCommand: npm install
    startCommand: node src/api/server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-url.netlify.app